FROM node:18.18-alpine as builder

# Build stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build:backend

# Production stage
FROM node:18.18-alpine
WORKDIR /app
COPY --from=builder /app/dist/api /app
COPY --from=builder /app/node_modules /app/node_modules
CMD ["node", "api/server.js"]
